<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrzioClashReport.Core\OrzioClashReport.Core.csproj" />
    <ProjectReference Include="..\OrzioClashReport.Input.NavisworksXml\OrzioClashReport.Input.NavisworksXml.csproj" />
    <ProjectReference Include="..\OrzioClashReport.Input.RunManifestJson\OrzioClashReport.Input.RunManifestJson.csproj" />
    <ProjectReference Include="..\OrzioClashReport.Output.Html\OrzioClashReport.Output.Html.csproj" />
    <ProjectReference Include="..\OrzioClashReport.Persistence.RunIndexJson\OrzioClashReport.Persistence.RunIndexJson.csproj" />
    <ProjectReference Include="..\OrzioClashReport.Persistence.RunSnapshotJson\OrzioClashReport.Persistence.RunSnapshotJson.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>orzioclash</AssemblyName>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>preview.1</VersionSuffix>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
